### ISSUE TITLE
--earliest-commit-date returns unrecognized argument error

### ISSUE THREAD

**Issue by dkorobtsov** [asharov/git-hammer#18]
Trying to run following init command:
```python3 -m githammer init-project test ~/dev/test --earliest-commit-date 2019-01-01```

Getting following response:
```
usage: githammer [-h]
                 {init-project,update-project,add-repository,list-projects,list-sources,graph,summary}
                 ...
githammer: error: unrecognized arguments: --earliest-commit-date 2019-01-01
```

**Comment by asharov** [comment]
Did you install with pip or did you clone the repository? The version that's installed with pip doesn't yet have the `--earliest-commit-date` option.

**Comment by dkorobtsov** [comment]
Installed with pip. It was not obvious from readme that it does not apply to pip version :)

**Comment by asharov** [comment]
Yeah, it's a bit of a tricky problem, since I like to have the documentation up-to-date, and I'd prefer not to have to change it only because I'm publishing a version. Officially, the documentation of the published version is at the package page https://pypi.org/project/git-hammer/ but people are not going to find that first.

Anyway, I published a new version, so now the version installable with pip should also have the `--earliest-commit-date` option. Thanks for trying it out!
