### ISSUE TITLE
Allow ignoring certain paths

### ISSUE THREAD

**Issue by gracenoah** [asharov/git-hammer#6]
I have a git repo with millions of lines of vendored go code. The vendor directory should be ignored in the analysis. Right now the first 1000 commits were processed in 12 minutes but I have 15000 commits, so the whole thing will take many hours to finish without the ability to ignore the vendor directory. #2 would also help with this

**Comment by asharov** [comment]
Hi, sorry about taking so long to reply. I hadn't realized Github wasn't notifying me about this repository.

If not every file in your repository should be considered, you can create a configuration file for it to define which files are your sources. If your vendor directory is clearly separated, then an appropriate setting of `sourceFiles` in the configuration file is probably enough to avoid it. And if not, you should be able to avoid it by adding it to the `excludedSourceFiles`.

I hope this helps, in case you're still interested.

**Comment by gracenoah** [comment]
Thanks! I tried excluding every file (by accident) and it was going at 1000 commits per minute. After including the relevant files, it's still very slow right now at only 300 commits per minute and it seems to slow down as the codebase grows over time. Even with the vendor directory ignored, processing the first 1000 commits is taking 4:40 mins. I'll keep it running for a few hours, but I'm not very hopeful that it will get very far because it's slowing down so fast. What's the biggest codebase this tool has been used on?

**Comment by gracenoah** [comment]
14 hours later, it's still going and it's going at 3 minutes per 20 commits.

**Comment by gracenoah** [comment]
It took 28 hours. The DB is 158 MB. I realized that I forgot to ignore one big auto-generated file, so the results were useless 😭

**Comment by asharov** [comment]
Thanks for the report and your patience! The commit processing speed should depend only on the size of the commit (number of files, sizes of files), not on the number of commits that have been processed. But this is maybe not correct, since I'm also seeing the processing time slowing down with later commits. I will need to look into this more, and I opened issue #26 to track it.

The largest repository (or actually group of repositories) I've tried had a total of 33000 commits, about 250000 source lines in total. Processing time for that was about 12 hours, but that was with the first released version. I think some of the work I've done since may have slowed down the processing but probably only by something like 10-20% at most. Also, that original run was with Postgres instead of SQLite in case that matters (it probably shouldn't).

I did get an idea now for a possible improvement to the commit processing time, tracked in issue #24 . And your last problem of forgetting something in the source configuration is now issue #25 . Sorry about what happened.

**Comment by gracenoah** [comment]
Wow! Thanks for responding to all these issues. I know this is a toy project so it's very much appreciated. I'm kicking off another run with the generated files ignored. I'll check up on it on Monday. I think we can close this issue though since files ARE being ignored as they should be.

**Comment by gracenoah** [comment]
With the giant generated files removed, it took only 10h!

**Comment by asharov** [comment]
Wow, that's quite a speedup! That big file must have been changing often.
